[package]
name = "nimbus"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.89"
ctor = "0.2.8"
fallible-iterator = "0.3.0"
env_logger = "0.11.5"
sqlite3-parser = { path = "../lemon-rs" }
indexmap = { path = "../indexmap" }
log = "0.4.22"

[dev-dependencies]
insta = "1.40.0"